[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'
on_i = 1

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'soramugi/auto-ctags.vim'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'Shougo/neosnippet.vim.git'
on_i = 1
on_ft = 'snipppet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
