[[plugins]]
repo = 'Shougo/ddc.nvim'

[[plugins]]
repo = 'Shougo/defx.nvim'

[[plugins]]
repo = 'Shougo/ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-ui-ff'

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'

[[plugins]]
repo = 'shougo/ddu-filter-matcher_substring'

[[plugins]]
repo = 'shougo/ddu-kind-file'

[[plugins]]
repo = 'Shougo/ddc.vim'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'neovim/nvim-lsp'

[[plugins]]
repo = 'neovim/nvim-lspconfig'

[[plugins]]
repo = 'neovim/nvim-lsp-installer'

[[plugins]]
repo = 'mattn/vim-goimports'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'itchyny/lightline.vim'

