[[plugins]]
repo = 'cespare/vim-toml'
on_ft  = 'toml'

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft  = 'ruby'

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = 'slim'

[[plugins]]
repo = 'Shougo/deoplete-rct'
on_ft = 'ruby'
